To use this branch, just rebase it to main, select which test modules you want to run and push to llowinge/main branch

diff --git a/.github/workflows/ci-build.yaml b/.github/workflows/ci-build.yaml
--- a/.github/workflows/ci-build.yaml
+++ b/.github/workflows/ci-build.yaml
@@ -23,6 +23,7 @@ on:
       - main
       - camel-main
       - quarkus-main
+      - enable-grpc-disabled-test
       - "[0-9]+.[0-9]+.x"
     paths-ignore:
       - '**.adoc'
@@ -89,7 +90,6 @@ env:
 
 jobs:
   pre-build-checks:
-    if: github.repository == 'apache/camel-quarkus'
     runs-on: ubuntu-latest
     outputs:
       continue-build: ${{ steps.pre-build-checks.outputs.continue-build }}
@@ -305,22 +305,26 @@ jobs:
           fi
 
           if [[ ${NATIVE_MODULES[@]} ]]; then
-            eval ./mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} clean verify \
-              -Dformatter.skip -Dimpsort.skip -Denforcer.skip \
-              -Dquarkus.native.builder-image.pull=missing \
-              -Pnative,docker,ci \
-              --fail-at-end \
-              -pl "${NATIVE_MODULES[*]}"
+            for i in {1..30}; do
+              echo "--- Running test attempt ${i} of 30 ---"
+              eval ./mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} clean verify \
+                -Dformatter.skip -Dimpsort.skip -Denforcer.skip \
+                -Dquarkus.native.builder-image.pull=missing \
+                -Pnative,docker,ci \
+                --fail-at-end \
+                -pl :camel-quarkus-integration-test-ftp
+              if [[ $? -ne 0 ]]; then
+                echo "Tests failed on attempt ${i}. Stopping the script."
+                exit 1 # Exit the entire script with an error code
+              fi
+              echo "Attempt ${i} was successful."
+            done
           fi
       - name: Report test failures
         uses: ./.github/actions/test-summary-report
         if: ${{ failure() }}
         with:
           test-report-xml-base-dir: integration-tests
-      - name: Fail if there are uncommitted changes
-        shell: bash
-        run: |
-          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; git diff; exit 1; }
 
   functional-extension-tests:
     runs-on: ubuntu-latest
@@ -543,10 +547,17 @@ jobs:
         shell: bash
         run: |
           cd integration-tests
-          ../mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} \
-            -Dskip-testcontainers-tests -Dformatter.skip -Dimpsort.skip -Denforcer.skip \
-            --fail-at-end \
-            clean verify
+          for i in {1..30}; do
+            echo "Running ${i} windows test"
+            ../mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} \
+              -Dskip-testcontainers-tests -Dformatter.skip -Dimpsort.skip -Denforcer.skip \
+              --fail-at-end \
+              clean verify -pl :camel-quarkus-integration-test-ftp
+            if [[ $? -ne 0 ]]; then
+                echo "Tests failed on attempt ${i}. Stopping the script."
+                exit 1 # Exit the entire script with an error code
+            fi
+          done
       - name: Report test failures
         uses: ./.github/actions/test-summary-report
         if: ${{ failure() }}
